// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat.post').default>>>>
    }
    '/api/download-order': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/download-order').default>>>>
    }
    '/api/favoritos/alias': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favoritos/alias').default>>>>
    }
    '/api/favoritos/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favoritos/list').default>>>>
    }
    '/api/favoritos/toggle': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favoritos/toggle').default>>>>
    }
    '/api/get-company-by-cnpj': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/get-company-by-cnpj').default>>>>
    }
    '/api/imgbb': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/imgbb').default>>>>
    }
    '/api/list-tables': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/list-tables').default>>>>
    }
    '/api/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login').default>>>>
    }
    '/api/produtos/details': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/produtos/details').default>>>>
    }
    '/api/produtos/distinct': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/produtos/distinct').default>>>>
    }
    '/api/produtos/facet-counts': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/produtos/facet-counts').default>>>>
    }
    '/api/produtos/get-by-ids': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/produtos/get-by-ids').default>>>>
    }
    '/api/produtos/search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/produtos/search').default>>>>
    }
    '/api/register-company': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/register-company').default>>>>
    }
    '/api/register-user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/register-user').default>>>>
    }
    '/api/send-email': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/send-email').default>>>>
    }
    '/api/table-schema': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/table-schema').default>>>>
    }
    '/api/test-connection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-connection').default>>>>
    }
    '/api/user/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/profile.get').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/profile').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}