-- Reordena fisicamente as colunas da tabela `produtos` para alinhar com a ordem do CSV

ALTER TABLE produtos
  MODIFY COLUMN categoria VARCHAR(100) AFTER id,
  MODIFY COLUMN codigo_erp VARCHAR(100) AFTER categoria,
  MODIFY COLUMN part_number VARCHAR(100) AFTER codigo_erp,
  MODIFY COLUMN fabricante VARCHAR(150) AFTER part_number,
  MODIFY COLUMN tipo_medicao VARCHAR(150) AFTER fabricante,
  MODIFY COLUMN diametro_montagem VARCHAR(100) AFTER tipo_medicao,
  MODIFY COLUMN posicao_montagem VARCHAR(100) AFTER diametro_montagem,
  MODIFY COLUMN conexao_instrumento VARCHAR(150) AFTER posicao_montagem,
  MODIFY COLUMN material_involucro VARCHAR(150) AFTER conexao_instrumento,
  MODIFY COLUMN material_internos VARCHAR(150) AFTER material_involucro,
  MODIFY COLUMN visor VARCHAR(100) AFTER material_internos,
  MODIFY COLUMN classe_exatidao VARCHAR(100) AFTER visor,
  MODIFY COLUMN unidade_leitura VARCHAR(50) AFTER classe_exatidao,
  MODIFY COLUMN faixa_trabalho VARCHAR(100) AFTER unidade_leitura,
  MODIFY COLUMN glicerina TINYINT(1) NOT NULL DEFAULT 0 AFTER faixa_trabalho,
  MODIFY COLUMN certificados JSON AFTER glicerina,
  MODIFY COLUMN tubo_sifao TINYINT(1) NOT NULL DEFAULT 0 AFTER certificados,
  MODIFY COLUMN selo_diafragma TINYINT(1) NOT NULL DEFAULT 0 AFTER tubo_sifao,
  MODIFY COLUMN contato_eletrico TINYINT(1) NOT NULL DEFAULT 0 AFTER selo_diafragma,
  MODIFY COLUMN valvula_isolamento TINYINT(1) NOT NULL DEFAULT 0 AFTER contato_eletrico,
  MODIFY COLUMN ncm VARCHAR(20) AFTER valvula_isolamento,
  MODIFY COLUMN estoque INT NOT NULL DEFAULT 0 AFTER ncm,
  MODIFY COLUMN preco DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER estoque,
  MODIFY COLUMN imagens JSON AFTER preco,
  MODIFY COLUMN ativo TINYINT(1) NOT NULL DEFAULT 1 AFTER imagens,
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER ativo,
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;