// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/11/2025, 11:26:18
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/plugins/**/*.{js,ts,mjs}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/composables/**/*.{js,ts,mjs}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/utils/**/*.{js,ts,mjs}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vendas2/Desktop/template-nuxt-supabase-tailwind-master/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;